### ISSUE TITLE
gh-pages README: Wrong example given for Backbone.sync in example

### ISSUE THREAD

**Issue by parasyte** [pubnub/backbone#1]
https://github.com/pubnub/backbone/blob/gh-pages/index.html#L107-113 provides the wrong instructions. This appears in a section called `Backbone.sync`, yet this method is not used in the provided example. Also notice the typo; `extenc` ;)

**Comment by dristic** [comment]
I fixed the typo. The example is using it properly. The collection uses the `sync` method in the background. Backbone.sync is never called directly in a Backbone application.

**Comment by parasyte** [comment]
Interesting! That wasn't clear, but then I'm not familiar with backbone internals.
