### ISSUE TITLE
WARNING! - No JSON.stringify()

### ISSUE THREAD

**Issue by icohen** [pubnub/backbone#2]
JSON.stringify is used in a few places on the published message like at 

https://github.com/pubnub/backbone/blob/master/backbone-pubnub.js#L130

but the docs warn not to do so 

https://github.com/pubnub/javascript/blob/master/README.md#warning---no-jsonstringify

**Comment by stephenlb** [comment]
than you!  good catch.

**Comment by dristic** [comment]
I have fixed this in the latest stuff. Some legacy things that found their way into my programming :)
