### ISSUE TITLE
Demo doesn't run locally when following instructions

### ISSUE THREAD

**Issue by whitmanc** [pubnub/backbone#4]
Running `bower install pubnub-backbone` and then opening index.html renders the errors shown below.

![screen shot 2014-09-24 at 3 57 10 pm](https://cloud.githubusercontent.com/assets/1023159/4397081/bfb49bac-443c-11e4-8987-4ececdbb0d77.jpg)

I think some files need to be compiled (.scss file, for example) and served.

Please let me know if I missed a common step :) looking forward to trying out pubnub-backbone

**Comment by whitmanc** [comment]
Needed to open index.html in `/dist`, not index.html from `/app` 

:) Closing

**Comment by stephenlb** [comment]
Ty!
